{% set name = "ory-client" %}
{% set version = "1.22.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7bb8f7c83d7a046ad1ba35da9f470d6679b2230159257f4e4a007a44def96423

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - urllib3 >=2.1.0
    - python-dateutil >=2.8.2
    - pydantic >=2
    - typing-extensions >=4.7.1

test:
  imports:
    - ory_client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ory/sdk
  summary: Ory APIs
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlbertDeFusco
    - mattkram
